version: '3.7'

services:
  rebrow:
    image: marian/rebrow
    ports:
      - "5001:5001"      
  redis-master:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: "master"
      ALLOW_EMPTY_PASSWORD: "yes"
  redis-replica:
    image: bitnami/redis
    ports: 
      - "6380:6379"
    environment:
      REDIS_REPLICATION_MODE: "slave"
      REDIS_MASTER_HOST: "redis-master"
      REDIS_MASTER_PORT_NUMBER: "6379"
      REDIS_MASTER_PASSWORD: ""
      ALLOW_EMPTY_PASSWORD: "yes"
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
